before_install:
    - ./admin/travis-install-deps.sh

env:
    - EXTRA_PACKAGES=
    - EXTRA_PACKAGES=cvs

script:
    - ./admin/travis-build.sh

notifications:
    email:
        - shtk-log@googlegroups.com
